backend:
  name: git-gateway
  branch: main
  identity_url: "https://ambothoughts.netlify.app/.netlify/identity"
  gateway_url: "https://ambothoughts.netlify.app/.netlify/git"

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
